include:
  - https://gitlab.com/techyminati/halium-generic-adaptation-build-tools/-/raw/master/gsi-port-ci.yml

variables:
  ROOTFS_URL: "https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
  OTA_CHANNEL: "20.04/arm64/android9plus/stable"

image: ubuntu:20.04

build:
  rules:
   - when: never

flashable:
  rules:
   - when: never

devel-flashable:
  rules:
   - when: never

build-salt:
  extends: build
  rules:
   - if: $CI_PIPELINE_SOURCE == "push"

devel-flashable-salt:
  extends: [devel-flashable]
  needs: [build-salt]
  rules:
   - if: $CI_PIPELINE_SOURCE == "push"
